// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxQ0QEUTOX58k-w7lnOhE4PYCNESe07VA',
    appId: '1:285738266939:web:1ea903441c2569dd0f471e',
    messagingSenderId: '285738266939',
    projectId: 'stylemind-ai-d14ec',
    authDomain: 'stylemind-ai-d14ec.firebaseapp.com',
    storageBucket: 'stylemind-ai-d14ec.firebasestorage.app',
    measurementId: 'G-PKJN6QV8YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5cGZuK1-V8Ncc4QyfUPGg0p3Vu5UbJfA',
    appId: '1:285738266939:android:c2b2c981c3cbf26d0f471e',
    messagingSenderId: '285738266939',
    projectId: 'stylemind-ai-d14ec',
    storageBucket: 'stylemind-ai-d14ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6s3TSsWp2kHSNjrfrVMybEV_VT6K9ZMg',
    appId: '1:285738266939:ios:46488292d54f50ea0f471e',
    messagingSenderId: '285738266939',
    projectId: 'stylemind-ai-d14ec',
    storageBucket: 'stylemind-ai-d14ec.firebasestorage.app',
    iosClientId: '285738266939-tklds7llt32alqqrihvokjmhenkv6kpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylemindAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6s3TSsWp2kHSNjrfrVMybEV_VT6K9ZMg',
    appId: '1:285738266939:ios:46488292d54f50ea0f471e',
    messagingSenderId: '285738266939',
    projectId: 'stylemind-ai-d14ec',
    storageBucket: 'stylemind-ai-d14ec.firebasestorage.app',
    iosClientId: '285738266939-tklds7llt32alqqrihvokjmhenkv6kpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylemindAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxQ0QEUTOX58k-w7lnOhE4PYCNESe07VA',
    appId: '1:285738266939:web:eb24c6019a49b36f0f471e',
    messagingSenderId: '285738266939',
    projectId: 'stylemind-ai-d14ec',
    authDomain: 'stylemind-ai-d14ec.firebaseapp.com',
    storageBucket: 'stylemind-ai-d14ec.firebasestorage.app',
    measurementId: 'G-RS6FFM6VK0',
  );
}
